config/routes.rb
Recruiting::Application.routes.draw do
  resources :events do
    member do
      post :addUser
      post :removeUser
    end
  end
  resources :jobs do
    get :autocomplete_skill_name, :on =>:collection
    member do
      post :changeAppStatus
      get :userApply
      get :userUnapply
    end
  end
  resources :search
  resources :user_verifications
  resources :organizations
  resources :users, :type => "User" do
    get :autocomplete_skill_name, :on => :collection 
  end
  resources :user_sessions
  get "verify", :controller => 'users', :action => 'verify'
  get "login", :controller => 'user_sessions', :action => 'new'
  get "logout", :controller => 'user_sessions', :action => 'destroy'
  get "/createRecruiter", :controller => 'users', :action => 'newRecruiter'
  post "/finishRecruiter", :controller => 'users', :action => 'finishRecruiter'
  post "user" => "users#create"

  get "/home", :controller => 'events', :action => 'index'
  root 'users#landing'
  post "/organizations/remove_attachment" => 'organizations#remove_attachment'
  post "/remove_attachment" => 'users#remove_attachment'
  post "/events/remove_attachment" => 'events#remove_attachment'

end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :organization
	has_many :jobapps
	has_many :users, through: :jobapps
	acts_as_taggable_on :skills, :courses
	MAX_NAME_LENGTH = 128
	validates :title, :presence => true, :length => {maximum: MAX_NAME_LENGTH}

	include PgSearch
	multisearchable :against => [:title, :description],
									:using => {
										:tsearch => { prefix: true, dictionary: 'english'}
									}
	pg_search_scope :search, 
									:against => [:title, :description],
									:associated_against => {
										:skills => [:name]
									},
									:using => {
										:tsearch => { prefix: true, dictionary: 'english'}
									}

  def self.text_search(query)
  	if query.present?
  		search(query)
  	else
  		Job.all
  	end
  end

	def addUser(id)
		u=User.find(id)
		if u.nil?
			return -1
		end
		self.users << u
		if self.users.last != u
			return -1
		end
		u.save
		self.save
		return 1
	end

	def removeUser(id)
		u=User.find(id)
		if u.nil?
			return -1
		end
		self.users.delete(u)
		if self.users.include?(u)
			return -1
		end
		u.save
		self.save
		return 1
	end

	def addSkillTag(str)
		if self.skill_list.include?(str)
			return 0
		end
		self.skill_list.add(str)
		if !(self.skill_list.include?(str))
			return -1
		end
		return 1
	end

	def addCourseTag(str)
		if self.course_list.include?(str)
			return 0
		end
		self.course_list.add(str)
		if !(self.course_list.include?(str))
			return -1
		end
		return 1
	end

	def removeSkillTag(str)
		if !self.skill_list.include?(str)
			return 0
		end
		self.skill_list.remove(str)
		if (self.skill_list.include?(str))
			return -1
		end
		return 1
	end

	def removeCourseTag(str)
		if !self.course_list.include?(str)
			return 0
		end
		self.course_list.remove(str)
		if (self.course_list.include?(str))
			return -1
		end
		return 1
	end

	def changeAppStatus(uid, newstat)
		usr=User.find(uid)
		if usr.nil? || !self.users.include?(usr)
			return -1
		else
			ja=Jobapp.find_by_user_id_and_job_id(uid, self[:id])
			if ja.nil?
				return -1
			end
			ja.status=newstat
			if !ja.save
				return -1
			end
			self.save
			usr.save
			return ja[:status]
		end
	end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :set_job, only: [:edit, :show, :update, :destroy, :changeAppStatus, :userApply, :userUnapply]
	autocomplete :skill, :name, :full=>true, :class_name => 'ActsAsTaggableOn::Tag'

	def index
		@jobs = Job.text_search(params[:search])
	end

	def new
		@job = Job.new
	end


	def userApply
		result=@job.addUser(current_user[:id])
		redirect_to current_user
	end

	def userUnapply
		result=@job.removeUser(current_user[:id])
		redirect_to current_user
	end



	def show
		@org=current_user.organizations.first
		users=@job.users
		@considering=[]
		@accepted=[]
		@rejected=[]
		users.each do |user|
			ja=Jobapp.find_by_user_id_and_job_id(user[:id], @job[:id])
			if ja[:status]==0 || (ja[:status]).nil?
				@considering << user
			elsif ja[:status]==1
				@accepted << user
			elsif ja[:status]==2
				@rejected << user
			end
		end

	end

	def create
		@job = Job.new(job_params)
		@job.skill_list = job_params[:skill_list]
		respond_to do |format|
			if @job.save
				current_user.organizations.first.jobs << @job
				format.html { redirect_to @job, notice: 'Job was succesfully created' }
				format.json { render action: 'show', status: :created, location:@job }
			else
				format.html { render action: 'new' }
				format.json { render json: @job.errors, status: :unprocessable_entity }
			end
		end
	end

	def edit
	end

	def update
		respond_to do |format|
			if @job.update(job_params)
				@job.skill_list = job_params[:skill_list]
				format.html { redirect_to @job, notice:'Successful update' }
				format.json { head :no_content}
			else
				format.html { render action: 'edit' }
				format.html { render json: @job.errors, status: :unprocessable_entity}
			end
		end
	end

	def changeAppStatus
		rdata=request.POST
		uid=rdata[:uid]
		if current_user.organizations.first != @job.organization
			redirect_to '/'
		end
		status=rdata[:status]
		@job.changeAppStatus(uid, status)
		redirect_to @job
	end

	def destroy
		org = @job.organization
		@job.destroy
    respond_to do |format|
	    format.html { redirect_to org }
	    format.json { head :no_content }
    end
	end

	private 
		def set_job
			@job = Job.find(params[:id])
		end

		def job_params
			params.require(:job).permit(:title, :description, :skill_list)
		end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :title %>
  <%= f.text_field :title, :placeholder => "Title", class: "w-input" %>
  <%= f.label :description %>
  <%= f.text_field :description, :placeholder => "Description", class: "w-input" %>
  <%= f.label :skills %>
  <%= f.autocomplete_field :skill_list, autocomplete_skill_name_jobs_path, :"data-delimiter" => ', ', :placeholder=> "Skills (comma separated)",class: "w-input" %>

  <div class="actions">
  	<%= f.submit 'Create', :class => "w-button" %>
  </div>
<% end %>


app/views/jobs/_update_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :title %>
  <%= f.text_field :title, :placeholder => "Title", class: "w-input" %>
  <%= f.label :description %>
  <%= f.text_field :description, :placeholder => "Description", class: "w-input" %>
  <%= f.label :skills %>
  <%= f.autocomplete_field :skill_list, autocomplete_skill_name_jobs_path, :"data-delimiter" => ', ', class: "w-input" %>
  <div class="actions">
  	<%= f.submit 'Update', :class => "w-button" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Edit Job</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
<!--   <link rel="stylesheet" type="text/css" href="css/normalize_events.css.scss">
  <link rel="stylesheet" type="text/css" href="css/webflow_events.css.scss">
  <link rel="stylesheet" type="text/css" href="css/eventsrecruit.webflow.css.scss"> -->
  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
</head>
<body>

  <div class="section hero">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 center">
          <div width="auto" height="auto">
                  </div>
        </div>
        <div class="w-col w-col-6 hero-column">
          <h2>Edit Job</h2>
          <%= render 'jobs/update_form' %>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
</body>
</html>

app/views/jobs/index.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Jobs</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
</head>
<body>

  <% @jobs.each do |job| %>
  <div class="section hero">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 center">
          <div width="auto" height="auto">
                    
                  </div>
        </div>
        <div class="w-col w-col-6 hero-column">
          <h2><%= job.title %></h2>
  <%= link_to 'Details', job, class:"button action" %></a>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <% end %>
  

</body>
</html>


app/views/jobs/new.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Job</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
  
</head>
<body>

  <div class="section hero">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 center">
          <div width="auto" height="auto">
                  </div>
        </div>
        <div class="w-col w-col-6 hero-column">
        	<h2>New Job</h2>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
</body>
</html>

app/views/jobs/show.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Job</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
</head>
<body>

  <div class="section hero">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 center">

          
          <div width="auto" height="auto">
                  </div>

        </div>
        <div align="left">


        <div class="w-col w-col-6 hero-column">
          <h2>Title: <%= @job.title %> <br>
       Description: <%=@job.description %> <br>
      Tags: <%=@job.skill_list %> <br>

    </h2>

       <% if @org==@job.organization and current_user.recruiter%>
          <h3>Considering</h3>
          <% for user in @considering%>
            <form action=<%= changeAppStatus_job_path %> method="post">
              <p><%= user.username %></p>
              <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> />
              <input type="hidden" name="uid" value=<%= user[:id] %> />
              Accept<input type="radio" name="status" value=1 />
              Reject<input type="radio" name="status" value=2 />
              <input type="submit" />
            </form>
          <%end %>
          <h3> Accepted</h3>
            <% for user in @accepted %>
              <p><%= user.username %></p>
            <% end %>
          <h3>Rejected</h3>
            <% for user in @rejected %>
              <p><%= user.username %></p>
            <% end %>

        <% end %>
       <% if current_user.recruiter and @job.organization == current_user.organizations.first %>
       <%= link_to 'Edit', edit_job_path, class:"button action" %>
       <%= link_to 'Delete', job_path(@job), method: "delete", class:"button action" %>
       <% end %>


       <% if !(current_user.recruiter) && !current_user.jobs.include?(@job)%>
          <%= link_to 'Apply', userApply_job_path, class:"button action" %>
       <% end %>
       <% if !(current_user.recruiter) && current_user.jobs.include?(@job)%>
          <h5 class="button action"> Already Applied </h5>
       <% end %>

      </div>
    </div>

          </div>
  </div>
  <hr>
</body>
</html>
        
       