config/routes.rb
Recruiting::Application.routes.draw do
  resources :events do
    member do
      post :addUser
      post :removeUser
    end
  end
  resources :jobs do
    get :autocomplete_skill_name, :on =>:collection
    member do
      post :changeAppStatus
      get :userApply
      get :userUnapply
    end
  end
  resources :search
  resources :user_verifications
  resources :organizations
  resources :users, :type => "User" do
    get :autocomplete_skill_name, :on => :collection 
  end
  resources :user_sessions
  get "verify", :controller => 'users', :action => 'verify'
  get "login", :controller => 'user_sessions', :action => 'new'
  get "logout", :controller => 'user_sessions', :action => 'destroy'
  get "/createRecruiter", :controller => 'users', :action => 'newRecruiter'
  post "/finishRecruiter", :controller => 'users', :action => 'finishRecruiter'
  post "user" => "users#create"

  get "/home", :controller => 'events', :action => 'index'
  root 'users#landing'
  post "/organizations/remove_attachment" => 'organizations#remove_attachment'
  post "/remove_attachment" => 'users#remove_attachment'
  post "/events/remove_attachment" => 'events#remove_attachment'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_attached_file :picture,
	 :storage => :dropbox,
	:dropbox_credentials => "#{Rails.root}/config/dropbox_config.yml",  
	:dropbox_options => {       
		:path => proc { |style| "#{style}/users/images/#{id}_#{picture.original_filename}"},
		:unique_filename => true
	 }

	 has_attached_file :resume,
	 :storage => :dropbox,
	:dropbox_credentials => "#{Rails.root}/config/dropbox_config.yml",
	:dropbox_options => {
		:path => proc { |style| "#{style}/users/resumes/#{id}_#{resume.original_filename}"},       
		:unique_filename => true
	 }

	validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	validates_attachment_content_type :resume, :content_type => ["application/pdf"]

	has_and_belongs_to_many :events
	has_and_belongs_to_many :organizations
	has_many :jobapps
	has_many :jobs, through: :jobapps

	acts_as_taggable_on :skills, :courses

	include PgSearch
	multisearchable :against => [:name],
									:using => {
										:tsearch => { prefix:true, dictionary:'english'}
									}
	pg_search_scope :search,
									:against => [:name],
									:associated_against => {
										:skills => [:name],
										:courses => [:name]
									},
									:using => {
										:tsearch => {prefix:true, dictionary:'english'}
									}

	acts_as_authentic do |config|
		config.perishable_token_valid_for = 24.hour
	end

  def self.text_search(query)
  	if query.present?
  		search(query)
  	else
  		User.all
  	end
  end


	def deliver_verification_instructions!
		reset_perishable_token!
		Notifier.verification_instructions(self).deliver!
	end

	def verify!
		self.verified = true
		self.save
	end

	def applyToJob(jid)
		jb=Job.find(jid)
		if jb.nil?
			return false
		elsif self.jobs.include?(jb)
			return false
		end
		self.jobs << jb
		ja=Jobapp.find_by_user_id_and_job_id(self[:id], jb[:id])
		if ja.nil?
			return false
		end
		ja.status=0
		return self.jobs.include?(jb)
	end

	def changeApplicantStatus(uid, jid, stat)
		job=Job.find(jid)
		user=User.find(uid)
		ja=Jobapp.find_by_user_id_and_job_id(uid, jid)
		if ja.nil? || job.nil? || user.nil?
			return false
		end
		if self[:recruiter]==false || self.organizations.first!=job.organization
			return false
		end
		ja.status=stat
		ja.save
		job.save
		user.save
		return true
	end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :disable_nav, only: [:landing, :newRecruiter, :verify]
  skip_before_filter :require_login, only: [:verify, :create, :newRecruiter, :finishRecruiter]
  
  autocomplete :skill, :name, :full=> true, :class_name => 'ActsAsTaggableOn::Tag'

  # GET /users
  # GET /users.json
  def index
    if params[:search].nil?
      @users = User.all
    else
      @users = User.text_search(params[:search])
    end
  end

  def landing
    @user = User.new
    @user_session = UserSession.new
    if not current_user.nil?
      if current_user.recruiter
        redirect_to current_user
      else
        redirect_to '/home'
      end
    end
  end

  def verify
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @events= @user.events
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if current_user[:id] != @user[:id]
      redirect_to current_user
    end
  end

  def newRecruiter
    @user = User.new
  end

  def finishRecruiter
    @user=User.new(user_params)
    data=request.POST
    choice=data[:org_choice]
    org=data[:organization]
    if org.nil? or org == ""
      redirect_to '/#recruitersignup'
      return
    end
    @organ=Organization.new()
    @user.recruiter=true
    if @user.valid?
      if choice == "join"
        @organ=Organization.find_by name: org
        if not @organ.nil?
          @user.save
          @user.organizations << @organ
          @user.deliver_verification_instructions!
          redirect_to '/verify'
          return
        end
      end
      if choice == "create"
        @organ=Organization.find_by name: org
        if not @organ.nil?
          redirect_to '/#recruitersignup'
          return
        else
          @organ=Organization.new()
          @organ.name=org
          if @organ.save
            @user.save
            @user.organizations << @organ
            @user.deliver_verification_instructions!  
            redirect_to '/verify'
            return
          end
        end
      end
    else
      redirect_to '/#recruitersignup'
      return
    end
  end
  
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.recruiter= false

    password = user_params[:password]
    password_confirmation = user_params[:password_confirmation]
    
    if (password != password_confirmation) 
        flash[:notice] = "Password and confirmation do not match!" 
        redirect_to "/#signup"
        return
    end

    if (@user.username.length < 4)
      flash[:notice] = "Username must be at least 4 characters!" 
      redirect_to "/#signup"
      return
    end

    if (@user.password.length < 4 or @user.password_confirmation.length < 4)
      flash[:notice] = "Passwords must be at least 4 characters!" 
      redirect_to "/#signup"
      return
    end
    # Extract last 13 characters to check if "@berkeley.edu"
    email = @user.email[@user.email.length-13, @user.email.length]
    regexMatch = /(@*\.berkeley.edu|@berkeley.edu)$/
    matchesFound = regexMatch.match(email)
    if matchesFound
      if @user.save
        #UserMailer.registration_confirmation(@user).deliver
        #flash[:notice] = "SUCCESS!"
        @user.deliver_verification_instructions!
        # format.html { redirect_to @user, notice: 'User was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @user }
        redirect_to "/verify"
      else
        # format.html { render action: 'new' }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
        flash[:notice] = "We are sorry but this username is already taken or an account with this email has already been registered." 
        redirect_to "/#signup"
      end
    else
      flash[:notice] = "Must log in with Berkeley email address"
      redirect_to "/#signup"
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    logger.debug
    
    email = user_params[:email]
    email = email[email.length-13, email.length]
    regexMatch = /(@*\.berkeley.edu|@berkeley.edu)$/
    matchesFound = regexMatch.match(email)
    if (!matchesFound and current_user.recruiter==0)
      flash[:notice] = "Update failed: Must use a *.berkeley.edu email address!"
      redirect_to :back
      return
    end

    respond_to do |format|
      if @user.update(user_params)
        @user.skill_list = user_params[:skill_list]
        @user.course_list = user_params[:course_list]
        format.html { redirect_to @user }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def changeAppStatus
    rdata=request.POST
    uid=rdata[:uid]
    jid=rdata[:jid]
    stat=rdata[:status]
    result=current_user.changeApplicantStatus(uid, jid, stat)
    if result==false
    end
  end

  def remove_attachment
    @user = User.find(params[:user])
    attachment_type = params[:attachment_type]
    if (attachment_type == "picture")
      @user.picture.destroy
      @user[:picture_file_name] = nil
      @user[:picture_content_type] = nil
      @user[:picture_file_size] = nil
      @user[:picture_updated_at] = nil
    elsif (attachment_type == "resume")
      @user.resume.destroy
      @user[:resume_file_name] = nil
      @user[:resume_content_type] = nil
      @user[:resume_file_size] = nil
      @user[:resume_updated_at] = nil
    end

    @user.save
    redirect_to :back
    return
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :gpa, :major, :minor, :name, :website, :graduating_year,
        :picture, :attachement_type, :resume, :skill_list, :course_list)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_editTemplate.html.erb
<%= form_for(@user, :html => {autocomplete:'off'}) do |f| %>
  <% if @user.errors.any? %>

      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>

  <% end %>


    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6">
          <div width="auto" height="auto">
        <%= render "users/upload_form", :f => f %>
          </div>
        </div>

        <div class="w-col w-col-6 hero-column";float:right>

    <% if !flash.empty? and !(flash.empty? == "SUCCESS!")%>
      <%= flash[:notice] %>
    <% end %>
    <%= f.label :username%>
    <%= f.text_field :username, :placeholder => "Username", class: "w-input" %>
    <%= f.label :name %>
    <%= f.text_field :name, :placeholder => "Name", class: "w-input" %>
    <%= f.label :email %>
    <%= f.text_field :email, :placeholder => "Email Address", class: "w-input" %>
    <%= f.label :password %>
    <%= f.password_field :password, :placeholder => "Password", class: "w-input" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :placeholder => "Password Confirm", class: "w-input"%>

    <% if not @user.recruiter %>
    <%= f.label :skills %>
    <%= f.autocomplete_field :skill_list, autocomplete_skill_name_users_path, :"data-delimiter" => ', ', class: "w-input" %>
    <%= f.label :major %>
    <%= f.text_field :major, :placeholder => "Major", class: "w-input" %>
    <%= f.label :websites %>
    <%= f.text_field :website, :placeholder => "Linkedin URL", class: "w-input" %>
    <%= f.label :graduating_year %>
    <%= f.text_field :graduating_year, :placeholder => "Graduating Year", class: "w-input" %>

<h4><div align="left">Resume: </div>
       <% if @user.resume.exists? %> 
        <div align="left">
        <a href=<%= @user.resume.url(:download => true) %> class="h4"><%= @user.resume_file_name %></a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to "Delete", {:controller => "users", :action => "remove_attachment", :user => @user.id, :attachment_type => "resume"}, :method => "post" %></div>
      <% end %></h4> 
      
<div class="fileupload fileupload-new" data-provides="fileupload">
   <div>
      <span class="btn btn-file">
      <span class="fileupload-new">Select Resume</span>
      <%= f.file_field :resume, :class => 'file_field' %>       </span>  
   </div>
</div>
<% end %>
    
    




        
        


      </div>
    </div>
<br>
  <div class="actions">
    <%= f.submit 'Update', :class => "w-button" %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'w-button' %> 
  </div>
  <% end %>
        </div>
  </div>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {autocomplete:'off'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if !flash.empty? and !(flash.empty? == "SUCCESS!")%>
  <%= flash[:notice] %>
<% end %>



    <%= f.label :username %>
    <%= f.text_field :username, :placeholder => "Username", class: "w-input" %>
    <%= f.label :email %>
    <%= f.text_field :email, :placeholder => "Email Address", class: "w-input" %>
    <%= f.label :password %>
    <%= f.password_field :password, :placeholder => "Password", class: "w-input" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :placeholder => "Password Confirm", class: "w-input"%>
  <div class="actions">
    <%= f.submit 'Sign Up', :class => "w-button" %>
  </div>
<% end %>

app/views/users/_newRecruiter.html.erb
<form accept-charset="UTF-8" action="/finishRecruiter" class="new_user" id="new_user" method="post">
  <div style="margin:0;padding:0;display:inline;height=50px"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value=<%= form_authenticity_token %> /></div>



    <label>Username</label>
    <input class="w-input" id="user_username" name="user[username]" placeholder="Username" type="text" />
    <label>Email</label>
    <input class="w-input" id="user_email" name="user[email]" placeholder="Email Address" type="text"/ autocomplete="off">
    <label>Password</label>
    <input class="w-input" id="user_password" name="user[password]" placeholder="Password" type="password" />
    <label>Password Confirmation</label>
    <input class="w-input" id="user_password_confirmation" name="user[password_confirmation]" placeholder="Password Confirm" type="password" />
    <label>Your Organization</label>
    <input type="radio" name="org_choice" value="join">Join Existing Organization<br>
	<input type="radio" name="org_choice" value="create">Create New Organization

    <input class="w-input" id="user_organization" name="organization" placeholder="Your Company" type="text" />

  <div class="actions">
    <input class="w-button" name="commit" type="submit" value="Sign Up" />
  </div>
</form>

app/views/users/_upload_form.html.erb
<%#= display_base_errors @user %>  
<div class="control-group">
   <%#= f.label :picture, :class => 'control-label' %>   
   <div class="controls">
      <h4><div align="left"><%= @user.username %></div></h4>
      <div class="fileupload fileupload-new" data-provides="fileupload">
         <!-- <div class="fileupload-preview thumbnail" style="width: 200px; height: 150px;"> -->
         <!-- </div>  -->
         <div>
            <% if @user.picture.exists? %>
              <img src=<%= @user.picture.url(:download => false) %> />
              <%= link_to "Delete", {:controller => "users", :action => "remove_attachment", :user => @user.id, :attachment_type => "picture"}, :method => "post" %>
            <% end %>
            <span class="btn btn-file">
            <span class="fileupload-new">Select Image</span>             
            <%= f.file_field :picture, :class => 'file_field' %>       </span>  
         </div>
      </div>
   </div>
</div>

app/views/users/edit.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Events</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
</head>
<body>
  <div class="section hero">
    <div class="w-container">
      <div class="w-row">
       <%= render 'users/editTemplate' %>
      </div>
    </div>
  </div>
  <hr>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

</body>
</html>

app/views/users/editTemplate.html.erb
<%= form_for(@user, :html => {autocomplete:'off'}) do |f| %>
  <% if @user.errors.any? %>

      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>

  <% end %>


    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6">
          <div width="auto" height="auto">
        <%= render "users/upload_form", :f => f %>
          </div>
        </div>

        <div class="w-col w-col-6 hero-column";float:right>

    <% if !flash.empty? and !(flash.empty? == "SUCCESS!")%>
      <%= flash[:notice] %>
    <% end %>
              <%= f.text_field :username, :placeholder => "Username", class: "w-input" %>

    <%= f.text_field :name, :placeholder => "Name", class: "w-input" %>

    <%= f.text_field :email, :placeholder => "Email Address", class: "w-input" %>

    <%= f.password_field :password, :placeholder => "Password", class: "w-input" %>

    <%= f.password_field :password_confirmation, :placeholder => "Password Confirm", class: "w-input"%>

    <% if not @user.recruiter %>

    <%= f.text_field :skill_list, :placeholder => "Skills (comma separated)", class: "w-input" %>

 

    <%= f.text_field :major, :placeholder => "Major", class: "w-input" %>



    <%= f.text_field :website, :placeholder => "Linkedin URL", class: "w-input" %>

    <%= f.text_field :graduating_year, :placeholder => "Graduating Year", class: "w-input" %>

<h4><div align="left">Resume: </div>
       <% if @user.resume.exists? %> 
        <div align="left">
        <a href=<%= @user.resume.url(:download => true) %> class="h4"><%= @user.resume_file_name %></a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to "Delete", {:controller => "users", :action => "remove_attachment", :user => @user.id, :attachment_type => "resume"}, :method => "post" %></div>
      <% end %></h4> 
      
<div class="fileupload fileupload-new" data-provides="fileupload">
   <div>
      <span class="btn btn-file">
      <span class="fileupload-new">Select Resume</span>
      <%= f.file_field :resume, :class => 'file_field' %>       </span>  
    <% end %>
   </div>
</div>

    
    




        
        


      </div>
    </div>
<br>
  <div class="actions">
    <%= f.submit 'Update', :class => "w-button" %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'w-button' %> 
  </div>
<% end %>
        </div>
  </div>

app/views/users/index.html.erb
    <div class="section hero">
    <h2>Users</h2>

    <div class="w-container">
      <% k=0 %>
      <% @users.each do |user| %>
        <% if k%4==0 %>
          <div class="w-row">
        <% end %>

        <div class="w-col w-col-3 w-col-small-6">
          
          <h3><h2><%= user.name %></h2></h3>
          <%= link_to 'Details', user, class:"button action" %></a>
          
        </div>

        <% if k%4==3 %>
          </div>
        <% end %>
        <% k=k+1 %>
      <% end %>
      <% if k%4 != 0 %>
        </div>
      <% end %>
  </div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Events</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
</head>
<body>
  <div class="section hero" >
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6">
          <div width="auto" height="auto">
          <% if @user.picture.exists? %>

            <img class="hero-image" src=<%= @user.picture.url(:download => false) %> width="auto" height="auto" alt="5307e81e663cb6142a000316_UC-BERKELEY.jpg">
            
          <% else %>
            <%= image_tag "default_user_image.png", class:"hero-image", width:"auto", height:"auto" %>
          <% end %>
          </div>
        </div>
        <div class="w-col w-col-6 hero-column">
          <% if not @user.recruiter %>
          <h2><%= @user.username %></h2>
          Name: <%= @user.name %><br>
    
          
          Major: <%= @user.major %><br>
          Graduating year:<%= @user.graduating_year %><br>
          
            Email: <%= @user.email %>
              
              <br>Skills: <%= @user.skill_list %>
              
              <br>Resume: <a href=<%= @user.resume.url(:download => true) %> ><%= @user.resume_file_name %></a> 
              <br><br>



          <%= link_to (image_tag "gfacebook.png", width:"40"), @user.website, class:"w-inline-block social-link" %>

          <%= link_to (image_tag "glinkedin.png", width:"40"), @user.website, class:"w-inline-block social-link" %>



      <br><br>


              <% end %>
         <% if @user.recruiter %>
         <h2><%= @user.username %></h2>
          Name: <%= @user.name %><br>
          Username:<%= @user.username %><br>
          Email: <%= @user.email %>


         <% end %>
              <% if @user == current_user %>
            </p><%= link_to 'Edit', edit_user_path, class:"button action" %></a>
            <% end %>
        </div>

 </div>
    </div>
  </div>
        
        

 <div class="section">
    <h2>Events</h2>
    <div class="w-container">
      <% k=0 %>
      <% @events.each do |event| %>
        <% if k%4==0 %>
          <div class="w-row">
        <% end %>

        <div class="w-col w-col-3 w-col-small-6">
          
          <h3><%= link_to event.name, event %></h3>
          <p><%= event.description %></p>

          
                  <% if event.event_picture.exists? %>
                  
                        <img class="hero-image" src=<%= event.event_picture.url(:download => false) %> width="auto" height="auto" alt="5307e81e663cb6142a000316_UC-BERKELEY.jpg" align="bottom">
                    <% else %>
                        <%= image_tag "UC-BERKELEY.jpg", class:"hero-image", width:"auto", height:"auto" %>    
                    <% end %>
          
        </div>

        <% if k%4==3 %>
          </div>
        <% end %>
        <% k=k+1 %>
      <% end %>
      <% if k%4 != 0 %>
        </div>
      <% end %>

<% if not @user.recruiter %>
<div class="section">
    <h2>Jobs</h2>
    <div class="w-container">
      <% k=0 %>
      <% @user.jobs.each do |job| %>
        <% if k%4==0 %>
          <div class="w-row">
        <% end %>

        <div class="w-col w-col-3 w-col-small-6">
          
          <% ja=Jobapp.find_by_user_id_and_job_id(@user[:id], job[:id]) %>
          <% status= ja[:status] %>
          <% if status==0 or status==nil %>
            <h3><%= link_to job.title, job, style:"color:#012E64" %></h3>
            <h5>Status: Pending</h5>
          <% end %>
          <% if status==1 %>
            <h3><%= link_to job.title, job, style:"color:green" %></h3>

            <h5>Status: Accepted</h5>
          <% end %>
          <% if status==2 %>
          <h3><%= link_to job.title, job, style:"color:red" %></h3>

            <h5>Status: Denied</h5>
          <% end %>
          <p><%= job.description %></p>
        </div>

        <% if k%4==3 %>
          </div>
        <% end %>
        <% k=k+1 %>
      <% end %>
      <% if k%4 != 0 %>
        </div>
      <% end %>
<% end %>
</body>
</html>

app/views/users/verify.html.erb
<html>
<title>Recruiting@Berkeley</title>
<body link="white" vlink="white" alink="white">
	
    <div class="nav-section">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-4">
          <div class="company"><a href="/" style="text-decoration : none; color : #FFFFFF;">Recruit Berkeley</a></div>
        </div>
        <div class="w-col w-col-8 navigation-column">
        </div>
      </div>
    </div>
  </div>
  <div class="container">
  <br><br><br>
  <center>
  	<h2>
  		You are one step away from Recruit@Berkeley <br><br><br>
  		<%= image_tag "Mail_deliver.jpg"%> <br><br><br>
	Please check your email for your email confirmation. 
	<br><br> PS : Be sure to check your spam folder  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :)
</h2>
</center>
</div>
</body>
</html>