config/routes.rb
Recruiting::Application.routes.draw do
  resources :events do
    member do
      post :addUser
      post :removeUser
    end
  end
  resources :jobs do
    get :autocomplete_skill_name, :on =>:collection
    member do
      post :changeAppStatus
      get :userApply
      get :userUnapply
    end
  end
  resources :search
  resources :user_verifications
  resources :organizations
  resources :users, :type => "User" do
    get :autocomplete_skill_name, :on => :collection 
  end
  resources :user_sessions
  get "verify", :controller => 'users', :action => 'verify'
  get "login", :controller => 'user_sessions', :action => 'new'
  get "logout", :controller => 'user_sessions', :action => 'destroy'
  get "/createRecruiter", :controller => 'users', :action => 'newRecruiter'
  post "/finishRecruiter", :controller => 'users', :action => 'finishRecruiter'
  post "user" => "users#create"

  get "/home", :controller => 'events', :action => 'index'
  root 'users#landing'
  post "/organizations/remove_attachment" => 'organizations#remove_attachment'
  post "/remove_attachment" => 'users#remove_attachment'
  post "/events/remove_attachment" => 'events#remove_attachment'

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_attached_file :event_picture,
	 	:storage => :dropbox,
		:dropbox_credentials => "#{Rails.root}/config/dropbox_config.yml",
	 	# :styles => { :medium => "300x300" , :thumb => "100x100>"},    
		:dropbox_options => {       
			:path => proc { |style| "#{style}/events/images/#{id}_#{event_picture.original_filename}"},
			:unique_filename => true
	 	}

	#belongs_to :organization
	has_and_belongs_to_many :users
	has_and_belongs_to_many :organizations

	MAX_NAME_LENGTH = 128
	MAX_LOCATION_LENGTH = 128
	MAX_DESCRIPTION_LENGTH = 512


	validates :name, :presence => true, :length => {maximum: MAX_NAME_LENGTH}
	validates :location, :presence => true, :length => {maximum: MAX_LOCATION_LENGTH}
	validates :description, :length => {maximum: MAX_DESCRIPTION_LENGTH}
	validates :date, :presence => true 
	validates_attachment_content_type :event_picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "application/pdf"]


	include PgSearch
	multisearchable :against => [:name, :description],
									:using => {
										:tsearch => { prefix: true, dictionary: 'english'}
									}
	pg_search_scope :search, 
									:against => [:name, :description],
									:using => {
										:tsearch => { prefix: true, dictionary: 'english'}
									}

  def self.text_search(query)
  	if query.present?
  		search(query)
  	else
  		Event.all
  	end
  end


	# deletes event with :id, returns 1 if successful delete otherwsie -1
	# Event.DeleteEvent(id)
	def self.DeleteEvent(id)
		event = Event.find_by_id(id)
		begin
			event.delete
			return 1
		rescue
			return -1
		end
	end


	# addes event with given input
	#def self.AddEvent(dict)
	#end


	# creates and relationship between a user and event (self)
	# Event.AddUserAttending(user)
	# def AddUser(user_id)
	# 	user = User.find_by_id(user_id)
	# 	if user.kind_of?(User) and not user.nil?
	# 		begin
	# 			self.users << user
	# 			return 1
	# 		rescue
	# 			return -1
	# 		end
	# 	else
	# 		return -1
	# 	end
	# end

	# removes a relationship between a user and event
	# Event.DeleteUserAttending(user)
	# def DeleteUser(user)
	# 	if user.kind_of?(User)
	# 		begin
	# 			self.users.delete(user)
	# 			return 1
	# 		rescue
	# 			return -1
	# 		end
	# 	else
	# 		return -1
	# 	end
	# end

	# creates a relationship between an event and recruiter
	# def AddRecruiter(user_id)
	# end

	# removes relationship between event and recruiter
	# def DeleteRecruiter(user_id)
	# end

	# creates a relationship between an event and an organization
	# def AddOrganization(organization)
	# 	if organization.kind_of?(Organization)
	# 		begin
	# 			self.organizations << organization
	# 			return 1
	# 		rescue
	# 			return -1
	# 		end
	# 	else
	# 		return -1
	# 	end
	# end

	# removes organization relationship with event
	# def DeleteOrganization(organization)
	# 	if organization.kind_of?(Organization)
	# 		begin
	# 			self.organizations.delete(organization)
	# 			return 1
	# 		rescue
	# 			return -1
	# 		end
	# 	else
	# 		return -1
	# 	end
	# end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :addUser, :removeUser]
  # GET /events
  # GET /events.json
  def index
    @events = Event.where(["date > ?", Date.today - 1]).order(date: :asc, created_at: :asc)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @user = current_user
  end

  def addUser
    if current_user.kind_of?(User) and not current_user.nil?
      begin
        @event.users << current_user
        redirect_to @event
      rescue
        redirect_to "/"
      end
    else
      redirect_to '/'
    end
  end

  def removeUser
    if current_user.kind_of?(User) and not current_user.nil?
      begin
        @event.users.delete(current_user)
        redirect_to @event
      rescue
        redirect_to "/"
      end
    else
      redirect_to '/'
    end
  end

  # GET /events/new
  def new
    @event = Event.new()
    # @event.type = params[:event_type]
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    logger.debug(params.inspect)
    @event = Event.new(event_params)
    dateTimeObj = DateTime.new(params[:date][:year].to_i,params[:date][:month].to_i,params[:date][:day].to_i,params[:date][:hour].to_i,params[:date][:minute].to_i)
    @event[:date] = dateTimeObj
    if (params[:speakers] != "")
      @event[:event_type] = "speaker_panel"
    end
    logger.debug @event.inspect
    respond_to do |format|
      if @event.save
        if current_user.recruiter
          @event.users << current_user
          @event.organizations << (current_user.organizations.first)
        end
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    org = @event.organizations.first
    @event.destroy
    respond_to do |format|
      format.html { redirect_to  org }
      format.json { head :no_content }
    end
  end

  def remove_attachment
    @event = Event.find(params[:event])
    @event.event_picture.destroy
    @event[:event_picture_file_name] = nil
    @event[:event_picture_content_type] = nil
    @event[:event_picture_file_size] = nil
    @event[:event_picture_updated_at] = nil

    @event.save
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :location, :eventdate, :description, :link, :speakers, :event_picture)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "new.js" %>
<% end %>

<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.text_field :name, :placeholder => "Name", class: "w-input" %><br>
<%= f.text_field :location, :placeholder => "Location", class: "w-input" %>

  <div class="field">
    <%= f.label :eventdate %><br>
    <%= select_datetime Date.today %>
  </div><br>
  <%= f.text_field :description, :placeholder => "Description", class: "w-input" %><br>
  <%= f.text_field :link, :placeholder => "Link", class: "w-input" %><br>

  <!-- Add fields to deal with speaker panels -->
  <%= label_tag("Speaker Panel? (Check to add speakers)") %>
  <%= check_box_tag(:hidden_speaker_panel) %>

  <div id="speakers_field" hidden="true">
    <%= f.text_field :speakers, :placeholder => "Speakers", class: "w-input", id:"speakers_field"%><br>
  </div>

  <%= render "events/upload_form", :f => f %>

  <div class="actions">
    <%= f.submit 'Create', :class => "w-button" %>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
  $("#event_speakers").val("")
  $("#hidden_speaker_panel").on("click", function (e) { 
    $("#speakers_field").style.display='none';
    $("#event_speakers").val("")
  })
})
</script>

app/views/events/_update_form.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "new.js" %>
<% end %>

<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.text_field :name, :placeholder => "Name", class: "w-input" %><br>
<%= f.text_field :location, :placeholder => "Location", class: "w-input" %>

  <div class="field">
    <%= f.label :eventdate %><br>
    <%= select_datetime Date.today %>
  </div><br>
  <%= f.text_field :description, :placeholder => "Description", class: "w-input" %><br>
  <%= f.text_field :link, :placeholder => "Link", class: "w-input" %><br>

  <!-- Add fields to deal with speaker panels -->
  <%= label_tag("Speaker Panel? (Check to add speakers)") %>
  <%= check_box_tag(:hidden_speaker_panel) %>

  <div id="speakers_field" hidden="true">
    <%= f.text_field :speakers, :placeholder => "Speakers", class: "w-input", id:"speakers_field"%><br>
  </div>

  <%= render "events/upload_form", :f => f %>

  <div class="actions">
    <%= f.submit 'Update', :class => "w-button" %>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
  $("#event_speakers").val("")
  $("#hidden_speaker_panel").on("click", function (e) { 
    $("#speakers_field").style.display='none';
    $("#event_speakers").val("")
  })
})
</script>

app/views/events/_upload_form.html.erb
<%#= display_base_errors @user %>  
<div class="control-group">
   <%#= f.label :picture, :class => 'control-label' %>   
   <div class="controls">
      <h4> Profile Picture upload </h4>
      <div class="fileupload fileupload-new" data-provides="fileupload">
         <div>
            <% if @event.event_picture.exists? %>
              <img src=<%= @event.event_picture.url(:download => false) %> />
              <%= link_to "Delete", {:controller => "events", :action => "remove_attachment", :event => @event.id, :attachment_type => "picture"}, :method => "post" %>
            <% end %>
            <span class="btn btn-file">
            <span class="fileupload-new">Select Image</span>             
            <%= f.file_field :event_picture, :class => 'file_field' %>       </span>  
         </div>
      </div>
   </div>
</div>

app/views/events/edit.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Events</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
</head>
<body>
  <div class="section hero">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 center">
          <div width="auto" height="auto">
                  </div>
        </div>
        <div class="w-col w-col-6 hero-column">
          <h2>Edit Event</h2>
          <%= render 'events/update_form' %>
        </div>
      </div>
    </div>
  </div>
  <hr>
</body>
</html>

app/views/events/index.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Events</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
</head>
<body>

  <% @events.each do |event| %>
  <div class="section hero">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 center">
          <div width="auto" height="auto">
                    <% if event.event_picture.exists? %>
                  
                        <%= image_tag event.event_picture %>
                    <% else %>
                        <%= image_tag "UC-BERKELEY.jpg", class:"hero-image", width:"auto", height:"auto" %>    
                    <% end %>



                  </div>
        </div>
        <div class="w-col w-col-6 hero-column">
          <h2><%= event.name %></h2>
          <p>Time: <%= event.date %>
            <br><p>Location: <%= event.location %>
            <br><p>Description: <%= event.description %><br><%= link_to 'Details', event, class:"button action" %></a>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <% end %>
  
</body>
</html>

app/views/events/new.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Events</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
</head>
<body>

  <div class="section hero">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 center">
          <div width="auto" height="auto">
                  </div>
        </div>
        <div class="w-col w-col-6 hero-column">
        	<h2>New Event</h2>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
  <hr>
</body>
</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Events</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
</head>
<body>
  <div class="section hero">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 center">
          <div width="auto" height="auto">


                  <% if @event.event_picture.exists? %>
                  
                        <img class="hero-image" src=<%= @event.event_picture.url(:download => false) %> width="auto" height="auto" alt="5307e81e663cb6142a000316_UC-BERKELEY.jpg">
                    <% else %>
                        <%= image_tag "UC-BERKELEY.jpg", class:"hero-image", width:"auto", height:"auto" %>    
                    <% end %>



                    
                  </div>
        </div>
        <div class="w-col w-col-6 hero-column">
          <h2><%= @event.name %></h2>
          <p>Time: <%= @event.date %><br>
            <p>Location: <%= @event.location %><br>
            <p>Food Present: <%= @event.foodPresent %><br>
            <p>Accepting Resumes: <%= @event.acceptingResumes %><br>
            <p>Number of Organizers: <%= @event.numberOfOrganizers %><br>
            <p>Description: <%= @event.description %><br>
            <% if (@event.event_type == "speaker_panel") %>
              <p>Speakers: <%= @event.speakers %><br>
            <% end %>
              <p> Users attending: <%= @event.users.size %>
              <% if not @user.recruiter %>
                <% if @user.events.exists?(@event)%>
                  <%= link_to 'Unfollow', removeUser_event_path, method: "post", class:"button action" %>
                <% else %>
                  <%= link_to 'Follow', addUser_event_path, method: "post", class:"button action" %>
                <% end %>
                <% end %>
                <% if not @user.recruiter %>
        <%= link_to 'Back', events_path, class:"button action" %>
        <% end %>
        <br>
        <% if @user.recruiter and @user.organizations.first.events.exists?(@event)%>
        <%= link_to 'Edit', edit_event_path, class:"button action" %>
        <%= link_to 'Delete', event_path(@event), method: "delete", class:"button action" %>
        <% end %>
        </div>
        

        
        
        <% if (@user.recruiter) %>
        <h4>Students Attending:</h4>
        <div id="" style="overflow-y: hidden; height:400px;">
          <% (@event.users).each do |user| %>
          <% if not user.recruiter %>
            </br>
            <% if user.picture.exists? %>
            <img src=<%= user.picture.url(:download => false) %> width="32px" height="32px" alt="5307e81e663cb6142a000316_UC-BERKELEY.jpg">  
            <% else %>
                  <%= image_tag "default_user_image.png", width:"32px", height:"32px" %>    
          <% end %>

         


            <%= link_to user.username, user %>
        


          <% end %>
          <% end %>
        <% else %>
        <h4>Recruiters Attending:</h4>
        <div id="" style="overflow-y: hidden; height:400px;">
          <% (@event.users).each do |user| %>
          <% if user.recruiter %>
            </br>
            <% if user.picture.exists? %>
            <img src=<%= user.picture.url(:download => false) %> width="32px" height="32px" alt="5307e81e663cb6142a000316_UC-BERKELEY.jpg">  
            <% else %>
                  <%= image_tag "default_user_image.png", width:"32px", height:"32px" %>           
          <% end %>
            <%= link_to user.username, user %><a/>
            
          <% end %>
          <% end %>
        <% end %>
        </div>



      </div>

    </div>

    
  </div>

  <hr>

</body>
</html>