config/routes.rb
Recruiting::Application.routes.draw do
  resources :events do
    member do
      post :addUser
      post :removeUser
    end
  end
  resources :jobs do
    get :autocomplete_skill_name, :on =>:collection
    member do
      post :changeAppStatus
      get :userApply
      get :userUnapply
    end
  end
  resources :search
  resources :user_verifications
  resources :organizations
  resources :users, :type => "User" do
    get :autocomplete_skill_name, :on => :collection 
  end
  resources :user_sessions
  get "verify", :controller => 'users', :action => 'verify'
  get "login", :controller => 'user_sessions', :action => 'new'
  get "logout", :controller => 'user_sessions', :action => 'destroy'
  get "/createRecruiter", :controller => 'users', :action => 'newRecruiter'
  post "/finishRecruiter", :controller => 'users', :action => 'finishRecruiter'
  post "user" => "users#create"

  get "/home", :controller => 'events', :action => 'index'
  root 'users#landing'
  post "/organizations/remove_attachment" => 'organizations#remove_attachment'
  post "/remove_attachment" => 'users#remove_attachment'
  post "/events/remove_attachment" => 'events#remove_attachment'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
    has_attached_file :organization_picture,
        :storage => :dropbox,
        :dropbox_credentials => "#{Rails.root}/config/dropbox_config.yml",
        :dropbox_options => {
            :path => proc { |style| "#{style}/organization/images/#{id}_#{organization_picture.original_filename}"},
            :unique_filename => true
        }

    validates_attachment_content_type :organization_picture, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	has_and_belongs_to_many :events
	has_and_belongs_to_many :users
	has_many :jobs
	MAX_NAME_LENGTH = 128
	validates :name, :presence => true, :length => {maximum: MAX_NAME_LENGTH}

	include PgSearch
    multisearchable :against => [:name],
                    :using => {
                        :tsearch => { prefix: true, dictionary: "english"}
                    }
	pg_search_scope :search, :against => [:name],
					:using => {
                    	:tsearch => {prefix: true, dictionary: "english"}
                  	}

    def self.text_search(query)
    	if query.present?
    		search(query)
    	else
    		Organization.all
    	end
    end

    def self.readySort(orgList)
        if orgList.nil? || orgList.length==0
            return []
        end
        newList=[]
        orgList.each do |org|
            sum=0
            jobs=org.jobs
            jobs.each do |job|
                sum += job.users.length
            end
            sum+= 10*(org.events.length)
            item=[org, sum]
            newList << item
        end
        return newList
    end

    def self.mergeSort(orgList)
        if orgList.nil? || orgList.length==0
            return []
        end
        if orgList.length==1
            return orgList
        end
        pivot=orgList.length/2
        left=orgList.slice(0, pivot)
        right=orgList.slice(pivot, orgList.length)
        left=self.mergeSort(left)
        right=self.mergeSort(right)
        newList=self.merge(left, right)
        return newList
    end

    def self.merge(left, right)
        newList=[]
        i=0
        j=0
        while (i<left.length && j<right.length) do
            if (left.at(i)).at(1) >= (right.at(j)).at(1)
                newList << left.at(i)
                i=i+1
            else
                newList << right.at(j)
                j=j+1
            end
        end

        if i<left.length
            while (i<left.length) do
                newList << left[i]
                i=i+1
            end
        else
            while (j<right.length) do
                newList << right[j]
                j=j+1
            end
        end
        return newList
    end


    def self.listConvert(orgList)
        newList=[]
        orgList.each do |org|
            newList << org[0]
        end
        return newList
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update]
  def index
  	@organizations=Organization.text_search(params[:search])
    # organizations=Organization.readySort(@organizations)
    # organizations=Organization.mergeSort(organizations)
    # @organizations=Organization.listConvert(organizations)
  end

  def show
  	@user=current_user
  	@user_org=@user.organizations
  	@events=@organization.events
  end

  def edit
  end

  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_attachment
    @org = Organization.find(params[:organization])
    @org.organization_picture.destroy
    @org[:organization_picture_file_name] = nil
    @org[:organization_picture_content_type] = nil
    @org[:organization_picture_file_size] = nil
    @org[:organization_picture_updated_at] = nil

    @org.save
    redirect_to :back
  end


private
  def set_organization
    @organization=Organization.find(params[:id])
  end

  def organization_params
      params.require(:organization).permit(:name, :location, :description, :link, :organization_picture)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_upload_form.html.erb
<%#= display_base_errors @user %>  
<div class="control-group">
   <%#= f.label :picture, :class => 'control-label' %>   
   <div class="controls">
      <h4> Profile Picture upload </h4>
      <div class="fileupload fileupload-new" data-provides="fileupload">
         <!-- <div class="fileupload-preview thumbnail" style="width: 200px; height: 150px;"> -->
         <!-- </div>  -->
         <div>
            <% if @organization.organization_picture.exists? %>
              <img src=<%= @organization.organization_picture.url(:download => false) %> />
              <%= link_to "Delete", {:controller => "organizations", :action => "remove_attachment", :organization => @organization.id, 
                :attachment_type => "picture"}, :method => "post" %>
            <% end %>
            <span class="btn btn-file">
            <span class="fileupload-new">Select Image</span>             
            <%= f.file_field :organization_picture, :class => 'file_field' %>       </span>  
         </div>
      </div>
   </div>
</div>

app/views/organizations/edit.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Events</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
</head>
<body>
  <div class="section hero">
    <div class="w-container">
      <div class="w-row">
      <h2>Edit Organization</h2>
    <%= render :template => 'organizations/editTemplate' %>
      </div>
    </div>
  </div>
  <hr>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
</body>
</html>

app/views/organizations/editTemplate.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>

      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>

  <% end %>
      <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6">
          <div width="auto" height="auto">
        <%= render "organizations/upload_form", :f => f %>
          </div>
        </div>
         <div class="w-col w-col-6 hero-column";float:right>
    <%= f.label :name %>
    <%= f.text_field :name, :placeholder => "Name", class: "w-input" %>
    <%= f.label :location %>
    <%= f.text_field :location, :placeholder => "Location", class: "w-input" %>
    <%= f.label :description %>
    <%= f.text_field :description, :placeholder => "Description", class: "w-input" %>
    <%= f.label :company_website %>
    <%= f.text_field :link, :placeholder => "Company Website", class: "w-input" %>

  <div class="actions">
    <%= f.submit 'Update', :class => "w-button" %>
  </div>
</div>
<% end %>

app/views/organizations/index.html.erb
<% @organizations.each do |organization| %>
	<h2><%= organization.name %></h2>
	<%= link_to 'Details', organization, class:"button action" %></a>
<% end %>

app/views/organizations/show.html.erb
<!DOCTYPE html>
<!-- This site was created in Webflow. http://www.webflow.com-->
<!-- Last Published: Fri Mar 14 2014 18:38:27 GMT+0000 (UTC) -->
<html data-wf-site="5307e34e3e274f132a000190">
<head>
  <meta charset="utf-8">
  <title>Events</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <link rel="shortcut icon" type="image/x-icon" href="https://y7v4p6k4.ssl.hwcdn.net/placeholder/favicon.ico">
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->
  <link rel="apple-touch-icon" href="https://y7v4p6k4.ssl.hwcdn.net/51e088cb308929c46c000051/51e1a444bceaf5b67b00004d_thumbnail-starter.png">
</head>
<body>
  
  <div class="section hero">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 center">
          <% if @organization.organization_picture.exists? %>
            <img class="hero-image" src=<%= @organization.organization_picture.url(:download => false) %> width="auto" height="auto" alt="5307e81e663cb6142a000316_UC-BERKELEY.jpg">
          <% end %>
        </div>
        <div class="w-col w-col-6 hero-column">
          <h2><%= @organization.name %></h2>
          <%= @organization.location %><br>
          <%= @organization.description %><br>
            <% if @organization == @user_org[0] %>
	<%= link_to 'Edit', edit_organization_path, class:"button action" %></a>
	<%= link_to 'Add Event', new_event_path, class:"button action" %></a>
  <%= link_to 'Add Job', new_job_path, class:"button action" %> 
<% end %>

        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>Events</h2>

    <div class="w-container">
      <% k=0 %>
      <% for event in (@organization.events) do %>
        <% if k%4==0 %>
          <div class="w-row">
        <% end %>

        <div class="w-col w-col-3 w-col-small-6">
          
          <h3><%= link_to event.name, event %></h3>
          <p><%= event.description %></p>
            <% if event.event_picture.exists? %>
                  
                        <img class="hero-image" src=<%= event.event_picture.url(:download => false) %> width="auto" height="auto" alt="5307e81e663cb6142a000316_UC-BERKELEY.jpg">
                    <% else %>
                        <%= image_tag "UC-BERKELEY.jpg", class:"hero-image", width:"auto", height:"auto" %>    
                    <% end %>



          
        </div>

        <% if k%4==3 %>
          </div>
        <% end %>
        <% k=k+1 %>
      <% end %>
      <% if k%4 != 0 %>
        </div>
      <% end %>
  </div>
  


  <div class="section">
        <h2>Jobs</h2><br>
    <div class="w-container">
      <% k=0 %>
      <% for job in (@organization.jobs) do %>
        <% if k%4==0 %>
          <div class="w-row">
        <% end %>

        <div class="w-col w-col-3 w-col-small-6">
          
          <h3><%= link_to job.title, job %></h3>
          <p><%= job.description %></p>
        </div>

        <% if k%4==3 %>
          </div>
        <% end %>
        <% k=k+1 %>
      <% end %>
      <% if k%4 != 0 %>
        </div>
      <% end %>



      
      
  </div>

</body>
</html>